import { DamageType } from './types/game';

export interface BestiarySpecies {
  id: string;
  nameVi: string;
  nameEn: string;
  family: 'slime' | 'greenskin' | 'undead' | 'elemental' | 'dragon';
  category: 'normal' | 'boss' | 'king' | 'mystery' | 'extinct';
  tier: 'normal' | 'elite' | 'champion' | 'king' | 'legend' | 'mythic' | 'ancient' | 'world-boss';
  baseLevel: number;
  color: string;
  weaknesses: DamageType[];
  skillVi: string;
  skillEn: string;
  loreVi: string;
  loreEn: string;
  hasCrown?: boolean;
  baseHpMult: number;
  baseAtkMult: number;
  baseDefMult: number;
  spawnMinStage: number;
  spawnMaxStage: number;
}

export const MONSTER_SPECIES_DATABASE: BestiarySpecies[] = [
  // ==========================================
  // 1. TIER: NORMAL (8 Monsters)
  // ==========================================
  {
    id: 's_meadow_slime',
    nameVi: 'Slime Thảo Nguyên',
    nameEn: 'Meadow Slime',
    family: 'slime',
    category: 'normal',
    tier: 'normal',
    baseLevel: 1,
    color: '#10b981',
    weaknesses: ['fire'],
    skillVi: 'Phun Bong Bóng',
    skillEn: 'Bubble Splash',
    loreVi: 'Loài Slime nguyên bản dẻo dai, sinh sống hòa bình tại các vùng thảo nguyên xanh mát.',
    loreEn: 'The original resilient Slime species, peacefully occupying open grasslands.',
    baseHpMult: 1.0,
    baseAtkMult: 1.0,
    baseDefMult: 1.0,
    spawnMinStage: 1,
    spawnMaxStage: 15
  },
  {
    id: 's_granite_slime',
    nameVi: 'Slime Cương Thạch',
    nameEn: 'Granite Slime',
    family: 'slime',
    category: 'normal',
    tier: 'normal',
    baseLevel: 8,
    color: '#78716c',
    weaknesses: ['ice'],
    skillVi: 'Giáp Đá Hóa Cương',
    skillEn: 'Stone Shielding',
    loreVi: 'Lõi đá thạch anh siêu cứng bảo vệ chúng khỏi các đòn chém vật lý nặng.',
    loreEn: 'Encased in heavy crystalline granite shield, protecting against physical thrusts.',
    baseHpMult: 1.3,
    baseAtkMult: 0.9,
    baseDefMult: 1.8,
    spawnMinStage: 5,
    spawnMaxStage: 25
  },
  {
    id: 's_magma_slime',
    nameVi: 'Slime Dung Nham',
    nameEn: 'Magma Slime',
    family: 'slime',
    category: 'normal',
    tier: 'normal',
    baseLevel: 15,
    color: '#ef4444',
    weaknesses: ['ice'],
    skillVi: 'Hỏa Cầu Bộc Phá',
    skillEn: 'Combustion Bomb',
    loreVi: 'Hấp thụ địa nhiệt từ nham thạch nung chảy, phóng ra những đốm lửa thiêu đốt đối thủ.',
    loreEn: 'Formed from underground molten magma, shooting explosive searing projectiles.',
    baseHpMult: 0.9,
    baseAtkMult: 1.5,
    baseDefMult: 0.8,
    spawnMinStage: 10,
    spawnMaxStage: 40
  },
  {
    id: 'g_forest_goblin',
    nameVi: 'Goblin Rừng Rậm',
    nameEn: 'Forest Goblin',
    family: 'greenskin',
    category: 'normal',
    tier: 'normal',
    baseLevel: 12,
    color: '#4ade80',
    weaknesses: ['fire', 'poison'],
    skillVi: 'Móc Túi Nhanh',
    skillEn: 'Quick Mug',
    loreVi: 'Sinh vật ranh ma thường núp bóng cây rừng để cướp bóc các đoàn lữ hành.',
    loreEn: 'Cunning tricksters hiding in dense tree shadows to pillage merchant caravans.',
    baseHpMult: 0.8,
    baseAtkMult: 1.2,
    baseDefMult: 0.7,
    spawnMinStage: 11,
    spawnMaxStage: 35
  },
  {
    id: 'g_orc_warrior',
    nameVi: 'Orc Chiến Binh',
    nameEn: 'Orc Warrior',
    family: 'greenskin',
    category: 'normal',
    tier: 'normal',
    baseLevel: 32,
    color: '#15803d',
    weaknesses: ['fire', 'ice'],
    skillVi: 'Cuồng Nộ Rìu Chiến',
    skillEn: 'Cleave Frenzy',
    loreVi: 'Đấu sĩ Orc đô con sở hữu sức mạnh cơ bắp đáng sợ, sẵn sàng nghiền nát mọi lá chắn.',
    loreEn: 'Heavy muscular orc gladiators wielding colossal waraxes to crush defenses.',
    baseHpMult: 1.4,
    baseAtkMult: 1.4,
    baseDefMult: 1.2,
    spawnMinStage: 31,
    spawnMaxStage: 65
  },
  {
    id: 'u_skeleton_archer',
    nameVi: 'Cung Thủ Xương',
    nameEn: 'Skeleton Archer',
    family: 'undead',
    category: 'normal',
    tier: 'normal',
    baseLevel: 25,
    color: '#cbd5e1',
    weaknesses: ['holy', 'fire'],
    skillVi: 'Mưa Tên Xương Khô',
    skillEn: 'Bone Arrow Rain',
    loreVi: 'Những cung thủ đã khuất phục sinh dưới tà thuật chiêu hồn, bắn ra mũi tên mang tử khí.',
    loreEn: 'Risen archers animated by necromancy, launching arrows coated in decay.',
    baseHpMult: 0.9,
    baseAtkMult: 1.3,
    baseDefMult: 0.9,
    spawnMinStage: 21,
    spawnMaxStage: 55
  },
  {
    id: 'e_stone_golem',
    nameVi: 'Golem Đá Cổ Đại',
    nameEn: 'Stone Golem',
    family: 'elemental',
    category: 'normal',
    tier: 'normal',
    baseLevel: 45,
    color: '#44403c',
    weaknesses: ['ice', 'dark'],
    skillVi: 'Chấn Động Đất Đá',
    skillEn: 'Earthquake Slam',
    loreVi: 'Hộ vệ đền cổ được khắc chữ rune cổ xưa, sừng sững bền bỉ như bàn thạch.',
    loreEn: 'Temple defenders inscribed with ancient runes, standing firm like mountain peaks.',
    baseHpMult: 1.8,
    baseAtkMult: 1.0,
    baseDefMult: 2.2,
    spawnMinStage: 41,
    spawnMaxStage: 85
  },
  {
    id: 'd_volcanic_drake',
    nameVi: 'Dực Long Núi Lửa',
    nameEn: 'Volcanic Drake',
    family: 'dragon',
    category: 'normal',
    tier: 'normal',
    baseLevel: 65,
    color: '#ea580c',
    weaknesses: ['ice', 'dark'],
    skillVi: 'Phún Trào Hỏa Long',
    skillEn: 'Fire Drake Breath',
    loreVi: 'Sinh vật có cánh thở ra tàn lửa nóng bỏng, thường săn mồi quanh các đỉnh núi lửa hoạt động.',
    loreEn: 'Winged predators nesting near active volcanic calderas, spewing cinder sprays.',
    baseHpMult: 1.2,
    baseAtkMult: 1.5,
    baseDefMult: 1.0,
    spawnMinStage: 61,
    spawnMaxStage: 95
  },

  // ==========================================
  // 2. TIER: ELITE (5 Monsters)
  // ==========================================
  {
    id: 's_frost_slime',
    nameVi: 'Slime Tuyết Lạnh',
    nameEn: 'Frost Slime',
    family: 'slime',
    category: 'normal',
    tier: 'elite',
    baseLevel: 22,
    color: '#3b82f6',
    weaknesses: ['fire'],
    skillVi: 'Hàn Băng Làm Chậm',
    skillEn: 'Freezing Slow',
    loreVi: 'Lớp tuyết lạnh vĩnh cửu bao phủ quanh thân, làm đóng băng và giảm tốc độ đánh mục tiêu.',
    loreEn: 'Coated in eternal freezing frost, slowing targets\' combat speed on contact.',
    baseHpMult: 1.1,
    baseAtkMult: 1.1,
    baseDefMult: 1.1,
    spawnMinStage: 18,
    spawnMaxStage: 50
  },
  {
    id: 's_void_slime',
    nameVi: 'Slime Hắc Ám',
    nameEn: 'Void Slime',
    family: 'slime',
    category: 'normal',
    tier: 'elite',
    baseLevel: 30,
    color: '#a855f7',
    weaknesses: ['holy'],
    skillVi: 'Bong Bóng Độc Hư Không',
    skillEn: 'Void Poison Bubble',
    loreVi: 'Sinh vật biến dị do hấp thụ tà khí hắc ám từ cõi hư vô sâu thẳm.',
    loreEn: 'Corrupted lifeforms that fed on dark void particles in deep rifts.',
    baseHpMult: 1.0,
    baseAtkMult: 1.3,
    baseDefMult: 1.0,
    spawnMinStage: 25,
    spawnMaxStage: 70
  },
  {
    id: 'g_orc_berserker',
    nameVi: 'Orc Berserker Cuồng Tín',
    nameEn: 'Orc Berserker',
    family: 'greenskin',
    category: 'normal',
    tier: 'elite',
    baseLevel: 36,
    color: '#b91c1c',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Rìu Cuồng Nộ',
    skillEn: 'Frenzy Cleave',
    loreVi: 'Những chiến binh Orc cuồng sát hung hãn, uống máu tuyết để gia tăng thể chất cực hạn.',
    loreEn: 'Frenzied orc warriors seeking bloodshed, harnessing winter chill to bypass limits.',
    baseHpMult: 1.3,
    baseAtkMult: 1.3,
    baseDefMult: 0.8,
    spawnMinStage: 35,
    spawnMaxStage: 75
  },
  {
    id: 'u_abyssal_wisp',
    nameVi: 'Linh Hồn Lửa Vực Sâu',
    nameEn: 'Abyssal Wisp',
    family: 'undead',
    category: 'normal',
    tier: 'elite',
    baseLevel: 55,
    color: '#f97316',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Đốt Cháy Tinh Linh',
    skillEn: 'Soul Cinder',
    loreVi: 'Tàn dư linh hồn những kẻ lạc lối bị giam cầm trong nham thạch nung chảy của Abyssal.',
    loreEn: 'Lost soul fragments condensed into blazing fire entities within Abyssal lava streams.',
    baseHpMult: 1.0,
    baseAtkMult: 1.4,
    baseDefMult: 0.9,
    spawnMinStage: 52,
    spawnMaxStage: 85
  },
  {
    id: 'e_quartz_golem',
    nameVi: 'Golem Thạch Anh Hào Quang',
    nameEn: 'Quartz Golem',
    family: 'elemental',
    category: 'normal',
    tier: 'elite',
    baseLevel: 24,
    color: '#d946ef',
    weaknesses: ['dark', 'physical'],
    skillVi: 'Tia Pha Lê Tán Xạ',
    skillEn: 'Refraction Beam',
    loreVi: 'Golem được cấu thành từ thạch anh tím tự nhiên, có khả năng hấp thụ và tán xạ tia sáng cực mạnh.',
    loreEn: 'Crystalline construct formed from rare quartz veins, reflecting spells with its prismatic body.',
    baseHpMult: 1.2,
    baseAtkMult: 1.1,
    baseDefMult: 1.5,
    spawnMinStage: 22,
    spawnMaxStage: 60
  },

  // ==========================================
  // 3. TIER: CHAMPION (5 Monsters)
  // ==========================================
  {
    id: 'g_goblin_vanguard',
    nameVi: 'Kỵ Sĩ Tiên Phong Goblin',
    nameEn: 'Goblin Vanguard',
    family: 'greenskin',
    category: 'king',
    tier: 'champion',
    baseLevel: 18,
    color: '#65a30d',
    weaknesses: ['fire', 'poison'],
    skillVi: 'Khiên Thép Đâm Thẳng',
    skillEn: 'Vanguard Charge',
    loreVi: 'Kẻ dẫn đầu thiết giáp binh đoàn Goblin, sử dụng khiên thép lớn càn quét quân thù.',
    loreEn: 'Heavily armored goblin vanguard leader, charging blindly to break enemy ranks.',
    hasCrown: true,
    baseHpMult: 3.4,
    baseAtkMult: 1.5,
    baseDefMult: 1.6,
    spawnMinStage: 15,
    spawnMaxStage: 30
  },
  {
    id: 'u_royal_skeleton',
    nameVi: 'Kiếm Sĩ Hoàng Gia Vong Hồn',
    nameEn: 'Royal Skeleton Sword',
    family: 'undead',
    category: 'king',
    tier: 'champion',
    baseLevel: 58,
    color: '#475569',
    weaknesses: ['holy', 'fire'],
    skillVi: 'Kiếm Khí Oán Hận',
    skillEn: 'Wraith Blade Strike',
    loreVi: 'Cận vệ hoàng triều sa đọa từ vương quốc cổ xưa phục sinh dưới tà thuật đen tối.',
    loreEn: 'Undead elite guards, wielding rusted imperial broadswords coated in lingering curses.',
    hasCrown: true,
    baseHpMult: 3.8,
    baseAtkMult: 1.8,
    baseDefMult: 1.5,
    spawnMinStage: 55,
    spawnMaxStage: 65
  },
  {
    id: 'g_orc_chieftain',
    nameVi: 'Orc Tộc Trưởng',
    nameEn: 'Orc Chieftain',
    family: 'greenskin',
    category: 'king',
    tier: 'champion',
    baseLevel: 40,
    color: '#166534',
    weaknesses: ['ice'],
    skillVi: 'Chiến Tiếng Rầm Rộ',
    skillEn: 'Warlord Roar',
    loreVi: 'Thủ lĩnh bộ tộc da xanh tàn bạo, được chọn qua hàng trăm cuộc sinh tử đấu đài vinh quang.',
    loreEn: 'The savage chief of greenskin clans, chosen through hundreds of death arena fights.',
    hasCrown: true,
    baseHpMult: 4.0,
    baseAtkMult: 2.0,
    baseDefMult: 1.6,
    spawnMinStage: 40,
    spawnMaxStage: 40
  },
  {
    id: 'e_wasp_queen',
    nameVi: 'Vua Ong Biến Dị Khổng Lồ',
    nameEn: 'Giant Wasp Queen',
    family: 'elemental',
    category: 'king',
    tier: 'champion',
    baseLevel: 10,
    color: '#ca8a04',
    weaknesses: ['fire', 'dark'],
    skillVi: 'Độc Châm Tê Liệt',
    skillEn: 'Paralyzing Sting',
    loreVi: 'Ong chúa biến dị có kích thước khổng lồ, sở hữu nọc độc làm tê liệt hệ tuần hoàn con mồi.',
    loreEn: 'Colossal hornet queen reigning over forest colonies, injecting slow-acting poison.',
    hasCrown: true,
    baseHpMult: 3.2,
    baseAtkMult: 1.7,
    baseDefMult: 1.2,
    spawnMinStage: 8,
    spawnMaxStage: 15
  },
  {
    id: 'e_cinder_general',
    nameVi: 'Tướng Quỷ Lửa Tro Tàn',
    nameEn: 'Cinder General',
    family: 'elemental',
    category: 'king',
    tier: 'champion',
    baseLevel: 56,
    color: '#b91c1c',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Mưa Thiên Thạch Lửa',
    skillEn: 'Cinder Rain Strike',
    loreVi: 'Cận vệ lửa thân tín của chúa tể Abyssal, cơ thể mang sức nóng khủng khiếp của tro tàn núi lửa.',
    loreEn: 'Abyssal elite general covered in melting volcano rocks, calling meteors from standard rifts.',
    hasCrown: true,
    baseHpMult: 3.6,
    baseAtkMult: 2.0,
    baseDefMult: 1.4,
    spawnMinStage: 55,
    spawnMaxStage: 70
  },

  // ==========================================
  // 4. TIER: KING (5 Monsters)
  // ==========================================
  {
    id: 's_slime_king',
    nameVi: 'Vua Slime Hoàng Gia',
    nameEn: 'Slime King',
    family: 'slime',
    category: 'king',
    tier: 'king',
    baseLevel: 10,
    color: '#eab308',
    weaknesses: ['fire'],
    skillVi: 'Vạn Quân Chấn Động',
    skillEn: 'Royal Slam',
    loreVi: 'Thủ lĩnh tối cao của đầm lầy Slime. Đội vương miện lấp lánh và nhảy đè bẹp kẻ khiêu khích.',
    loreEn: 'The absolute ruler of slimes, crushing challenges with high-altitude jumps.',
    hasCrown: true,
    baseHpMult: 3.5,
    baseAtkMult: 1.8,
    baseDefMult: 1.4,
    spawnMinStage: 10,
    spawnMaxStage: 10
  },
  {
    id: 'g_goblin_emperor',
    nameVi: 'Hoàng Đế Goblin',
    nameEn: 'Goblin Emperor',
    family: 'greenskin',
    category: 'king',
    tier: 'king',
    baseLevel: 20,
    color: '#84cc16',
    weaknesses: ['fire'],
    skillVi: 'Lệnh Triệu Tập Binh Sĩ',
    skillEn: 'Emperor Summon',
    loreVi: 'Thống trị toàn bộ vương quốc da xanh dưới lòng đất, chỉ huy hàng vạn tay sai phục dịch.',
    loreEn: 'Ruler of the subterranean greenskin empire, commanding hordes of loyal minions.',
    hasCrown: true,
    baseHpMult: 3.8,
    baseAtkMult: 1.9,
    baseDefMult: 1.5,
    spawnMinStage: 20,
    spawnMaxStage: 20
  },
  {
    id: 'u_skeleton_warlord',
    nameVi: 'Bạo Chúa Xương Warlord',
    nameEn: 'Skeleton Warlord',
    family: 'undead',
    category: 'king',
    tier: 'king',
    baseLevel: 30,
    color: '#94a3b8',
    weaknesses: ['holy'],
    skillVi: 'Tử Khí Trỗi Dậy',
    skillEn: 'Rise of Undead',
    loreVi: 'Chủ tướng đại quân xác sống cổ đại. Thanh kiếm rỉ sét của hắn đã uống máu hàng vạn sinh linh.',
    loreEn: 'Commander of ancient undead legions, wielding a cursed heavy claymore.',
    hasCrown: true,
    baseHpMult: 4.2,
    baseAtkMult: 2.1,
    baseDefMult: 1.6,
    spawnMinStage: 30,
    spawnMaxStage: 30
  },
  {
    id: 'u_wraith_lord',
    nameVi: 'Chúa Tể Hồn Ma Wraith',
    nameEn: 'Wraith Lord',
    family: 'undead',
    category: 'king',
    tier: 'king',
    baseLevel: 60,
    color: '#6366f1',
    weaknesses: ['holy', 'fire'],
    skillVi: 'Hồn Hút Hư Vô',
    skillEn: 'Soul Drain',
    loreVi: 'Vua của thế giới linh hồn vất vưởng, một tiếng thét oán than có thể bóp nghẹt tâm trí kẻ thù.',
    loreEn: 'Sovereign of lost spirits, shattering resolve with echoes of eternal torment.',
    hasCrown: true,
    baseHpMult: 4.5,
    baseAtkMult: 2.2,
    baseDefMult: 1.7,
    spawnMinStage: 60,
    spawnMaxStage: 60
  },
  {
    id: 'e_demon_commander',
    nameVi: 'Thống Lĩnh Quỷ Lửa',
    nameEn: 'Demon Commander',
    family: 'elemental',
    category: 'king',
    tier: 'king',
    baseLevel: 70,
    color: '#dc2626',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Địa Ngục Phẫn Nộ',
    skillEn: 'Hellfire Wrath',
    loreVi: 'Đại tướng quân xứ Abyssal, thống lĩnh binh đoàn quỷ lửa thiêu rụi các lục địa.',
    loreEn: 'Arch-general of abyssal voids, command fire demons to burn civilizations.',
    hasCrown: true,
    baseHpMult: 5.2,
    baseAtkMult: 2.5,
    baseDefMult: 1.8,
    spawnMinStage: 70,
    spawnMaxStage: 70
  },

  // ==========================================
  // 5. TIER: LEGEND (5 Monsters)
  // ==========================================
  {
    id: 'd_ancient_dragon',
    nameVi: 'Cổ Long Băng Giá (Boss)',
    nameEn: 'Ancient Dragon',
    family: 'dragon',
    category: 'boss',
    tier: 'legend',
    baseLevel: 90,
    color: '#0284c7',
    weaknesses: ['fire', 'dark'],
    skillVi: 'Hơi Thở Hàn Băng Tuyệt Diệt',
    skillEn: 'Absolute Zero Breath',
    loreVi: 'Rồng cổ đại sống ngàn năm trong băng tuyết vĩnh cửu. Một hơi thở đóng băng vạn vật.',
    loreEn: 'Thousand-year-old dragon sleeping in glacial peaks, turning challengers into solid ice.',
    hasCrown: true,
    baseHpMult: 6.0,
    baseAtkMult: 3.0,
    baseDefMult: 2.2,
    spawnMinStage: 90,
    spawnMaxStage: 90
  },
  {
    id: 'd_drake_sovereign',
    nameVi: 'Chúa Tể Dực Long',
    nameEn: 'Drake Sovereign',
    family: 'dragon',
    category: 'king',
    tier: 'legend',
    baseLevel: 80,
    color: '#c2410c',
    weaknesses: ['ice'],
    skillVi: 'Hơi Thở Tàn Phá',
    skillEn: 'Sovereign Breath',
    loreVi: 'Vua của loài dực long núi lửa, thống trị bầu trời rực lửa bằng uy áp long tộc cổ đại.',
    loreEn: 'Overlord of volcanic drakes, ruling the burning sky with imperial dragon presence.',
    hasCrown: true,
    baseHpMult: 5.5,
    baseAtkMult: 2.7,
    baseDefMult: 2.0,
    spawnMinStage: 80,
    spawnMaxStage: 80
  },
  {
    id: 'd_swamp_wyrm',
    nameVi: 'Rồng Đầu Độc Đầm Lầy',
    nameEn: 'Swamp Venom Wyrm',
    family: 'dragon',
    category: 'boss',
    tier: 'legend',
    baseLevel: 75,
    color: '#0f766e',
    weaknesses: ['ice', 'fire'],
    skillVi: 'Phun Độc Axit',
    skillEn: 'Acidic Venom Breath',
    loreVi: 'Con rồng đầm lầy khổng lồ mang hơi thở axit có khả năng nung chảy cả giáp sắt kiên cố nhất.',
    loreEn: 'Colossal wyrm living in acid swamps, melting target armors with acid spray.',
    hasCrown: true,
    baseHpMult: 5.8,
    baseAtkMult: 2.8,
    baseDefMult: 1.8,
    spawnMinStage: 75,
    spawnMaxStage: 75
  },
  {
    id: 'u_death_knight',
    nameVi: 'Kỵ Sĩ Khải Huyền Tử Vong',
    nameEn: 'Death Knight Lord',
    family: 'undead',
    category: 'boss',
    tier: 'legend',
    baseLevel: 48,
    color: '#020617',
    weaknesses: ['holy'],
    skillVi: 'Hơi Thở Tử Vong',
    skillEn: 'Decay Necrotic Aura',
    loreVi: 'Kỵ sĩ khải huyền cưỡi trên chiến mã rực tử khí, càn quét tàn bạo qua các vùng đất thần tiên.',
    loreEn: 'A powerful death knight commander riding an undead steed, emitting necrotic cold aura.',
    hasCrown: true,
    baseHpMult: 5.2,
    baseAtkMult: 2.5,
    baseDefMult: 2.0,
    spawnMinStage: 48,
    spawnMaxStage: 48
  },
  {
    id: 'd_half_dragon',
    nameVi: 'Bán Long Nhân Cuồng Bạo',
    nameEn: 'Fierce Half-Dragon',
    family: 'dragon',
    category: 'king',
    tier: 'legend',
    baseLevel: 72,
    color: '#7f1d1d',
    weaknesses: ['ice', 'dark'],
    skillVi: 'Móng Vuốt Long Tộc',
    skillEn: 'Dragon Claw Strike',
    loreVi: 'Chiến binh rồng lai mang trong mình dòng máu long tộc nguyên thủy dũng mãnh và cuồng bạo.',
    loreEn: 'Draconic demi-human warrior wielding dual longdaggers, protected by scales.',
    hasCrown: true,
    baseHpMult: 3.8,
    baseAtkMult: 2.2,
    baseDefMult: 1.5,
    spawnMinStage: 68,
    spawnMaxStage: 80
  },

  // ==========================================
  // 6. TIER: MYTHIC (5 Monsters)
  // ==========================================
  {
    id: 's_ancient_slime_god',
    nameVi: 'Thần Slime Cổ Đại Canh Giữ (Huyền Thoại)',
    nameEn: 'Primordial Slime God',
    family: 'slime',
    category: 'extinct',
    tier: 'mythic',
    baseLevel: 50,
    color: '#4f46e5',
    weaknesses: ['holy', 'dark'],
    skillVi: 'Hào Quang Hỗn Hợp',
    skillEn: 'Primordial Aura Burst',
    loreVi: 'Tổ mẫu tối cổ của vạn vật dẻo dai. Thần thức của nó trỗi dậy khi người chơi tiêu diệt hơn 100 Slime.',
    loreEn: 'Primordial deity of gelatinous organisms. Awakens when Meadow Slime species drops critical numbers.',
    hasCrown: true,
    baseHpMult: 7.5,
    baseAtkMult: 3.0,
    baseDefMult: 2.0,
    spawnMinStage: 999,
    spawnMaxStage: 999
  },
  {
    id: 's_crystal_slime',
    nameVi: 'Slime Pha Lê',
    nameEn: 'Crystal Slime',
    family: 'slime',
    category: 'mystery',
    tier: 'mythic',
    baseLevel: 35,
    color: '#06b6d4',
    weaknesses: ['dark'],
    skillVi: 'Tinh Thể Phản Chiếu',
    skillEn: 'Reflective Spike',
    loreVi: 'Slime hiếm có vỏ bọc pha lê lấp lánh phản chiếu ma pháp. Chỉ gặp ở các ải pha lê sâu.',
    loreEn: 'A rare crystal-coated Slime that refracts magic spells. Found in deep crystalline caves.',
    baseHpMult: 1.2,
    baseAtkMult: 1.2,
    baseDefMult: 1.5,
    spawnMinStage: 30,
    spawnMaxStage: 100
  },
  {
    id: 's_golden_slime',
    nameVi: 'Slime Hoàng Kim (Hiếm)',
    nameEn: 'Golden Slime',
    family: 'slime',
    category: 'mystery',
    tier: 'mythic',
    baseLevel: 10,
    color: '#fbbf24',
    weaknesses: ['dark', 'fire'],
    skillVi: 'Hào Quang Tài Lộc',
    skillEn: 'Fortune Glow',
    loreVi: 'Sinh vật huyền thoại làm bằng vàng ròng, cực kỳ nhanh nhẹn và giàu có khi tiêu diệt.',
    loreEn: 'A legendary slime made of pure gold. Extremely fast and yields huge wealth when slain.',
    baseHpMult: 2.0,
    baseAtkMult: 0.5,
    baseDefMult: 2.0,
    spawnMinStage: 1,
    spawnMaxStage: 1000
  },
  {
    id: 'd_void_dragon',
    nameVi: 'Cổ Long Hư Không Vĩnh Hằng',
    nameEn: 'Void Eternity Dragon',
    family: 'dragon',
    category: 'boss',
    tier: 'mythic',
    baseLevel: 95,
    color: '#312e81',
    weaknesses: ['holy'],
    skillVi: 'Hố Đen Hủy Diệt',
    skillEn: 'Event Horizon Nebula',
    loreVi: 'Sinh vật thần thoại bơi trong dòng thời gian đen tối, hấp thụ hoàn toàn tinh tú và ánh sáng.',
    loreEn: 'Mythical dragon soaring through dimensional boundaries, tearing reality apart with void holes.',
    hasCrown: true,
    baseHpMult: 7.0,
    baseAtkMult: 3.5,
    baseDefMult: 2.0,
    spawnMinStage: 95,
    spawnMaxStage: 95
  },
  {
    id: 'd_phoenix_god',
    nameVi: 'Phượng Hoàng Lửa Bất Tử',
    nameEn: 'Eternal Phoenix God',
    family: 'dragon',
    category: 'boss',
    tier: 'mythic',
    baseLevel: 99,
    color: '#f43f5e',
    weaknesses: ['ice', 'dark'],
    skillVi: 'Phượng Hoàng Tái Sinh',
    skillEn: 'Eternal Rebirth Flare',
    loreVi: 'Thần điểu sinh ra từ tia lửa sơ khai, tái sinh từ đống tro tàn với sức mạnh thiêu đốt sinh mệnh.',
    loreEn: 'Immortal firebird reemerging from volcanic embers, healing itself through solar combustion.',
    hasCrown: true,
    baseHpMult: 6.5,
    baseAtkMult: 3.8,
    baseDefMult: 1.8,
    spawnMinStage: 99,
    spawnMaxStage: 99
  },

  // ==========================================
  // 7. TIER: ANCIENT (5 Monsters)
  // ==========================================
  {
    id: 'e_golem_guardian',
    nameVi: 'Hộ Vệ Golem Khổng Lồ',
    nameEn: 'Golem Guardian',
    family: 'elemental',
    category: 'king',
    tier: 'ancient',
    baseLevel: 50,
    color: '#292524',
    weaknesses: ['ice'],
    skillVi: 'Rào Chắn Thiên Thạch',
    skillEn: 'Meteor Barrier',
    loreVi: 'Golem tối cổ canh giữ cổng thần giới, thân thể làm bằng kim loại thiên thạch siêu cứng bất hoại.',
    loreEn: 'Ancient construct guarding celestial gates, made of meteor alloy.',
    hasCrown: true,
    baseHpMult: 4.8,
    baseAtkMult: 2.3,
    baseDefMult: 1.8,
    spawnMinStage: 50,
    spawnMaxStage: 50
  },
  {
    id: 'e_golem_chieftain',
    nameVi: 'Tộc Trưởng Người Đá Cổ',
    nameEn: 'Golem Chieftain',
    family: 'elemental',
    category: 'king',
    tier: 'ancient',
    baseLevel: 46,
    color: '#451a03',
    weaknesses: ['ice'],
    skillVi: 'Địa Chấn Vỡ Vụn',
    skillEn: 'Shattering Ground',
    loreVi: 'Đầu lĩnh của cự thạch tộc linh hồn cổ xưa, kiểm soát các rung chấn mạnh mẽ dưới lòng đất.',
    loreEn: 'Leader of geological elemental constructs, capable of triggering heavy earthquakes.',
    hasCrown: true,
    baseHpMult: 4.5,
    baseAtkMult: 1.6,
    baseDefMult: 2.0,
    spawnMinStage: 45,
    spawnMaxStage: 55
  },
  {
    id: 'u_ancient_lich',
    nameVi: 'Hoàng Đế Lich Cổ Đại',
    nameEn: 'Ancient Lich Emperor',
    family: 'undead',
    category: 'king',
    tier: 'ancient',
    baseLevel: 82,
    color: '#4c1d95',
    weaknesses: ['holy', 'fire'],
    skillVi: 'Ma Pháp Hắc Ám Hủy Diệt',
    skillEn: 'Necrotic Eclipse Magic',
    loreVi: 'Phù thủy hắc ám đạt tới ngưỡng bất tử vĩnh hằng, thống lĩnh toàn cõi vương quốc xác sống.',
    loreEn: 'Wizard who casted forbidden spells to gain immortality, commanding legions of skeletons.',
    hasCrown: true,
    baseHpMult: 4.8,
    baseAtkMult: 2.8,
    baseDefMult: 1.5,
    spawnMinStage: 82,
    spawnMaxStage: 82
  },
  {
    id: 'e_corrupted_treant',
    nameVi: 'Thần Thụ Cổ Đại Sa Đọa',
    nameEn: 'Corrupted Treant',
    family: 'elemental',
    category: 'boss',
    tier: 'ancient',
    baseLevel: 26,
    color: '#064e3b',
    weaknesses: ['fire', 'dark'],
    skillVi: 'Rễ Cây Trói Buộc',
    skillEn: 'Root Entangle Slap',
    loreVi: 'Thần cây ngàn năm tuổi của rừng thiêng bị tha hóa hoàn toàn khi tà khí hư không rò rỉ.',
    loreEn: 'Ancient forest spirit corrupted by leaked dark void essence, crushing invaders with its giant roots.',
    hasCrown: true,
    baseHpMult: 5.5,
    baseAtkMult: 2.2,
    baseDefMult: 1.8,
    spawnMinStage: 25,
    spawnMaxStage: 25
  },
  {
    id: 'e_abyss_archdemon',
    nameVi: 'Đại Quỷ Vương Abyssal',
    nameEn: 'Abyss Archdemon Lord',
    family: 'elemental',
    category: 'king',
    tier: 'ancient',
    baseLevel: 88,
    color: '#7f1d1d',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Hỏa Ngục Hủy Diệt',
    skillEn: 'Apocalyptic Inferno Burst',
    loreVi: 'Đại chúa tể sâu thẳm trong Abyssal, mang ngọn lửa thần tà ác đốt cháy lương tri con người.',
    loreEn: 'Ruler of the deepest abyssal rings, burning civilizations with everlasting hellfires.',
    hasCrown: true,
    baseHpMult: 5.4,
    baseAtkMult: 3.0,
    baseDefMult: 1.6,
    spawnMinStage: 88,
    spawnMaxStage: 88
  },

  // ==========================================
  // 8. TIER: WORLD BOSS (5 Monsters)
  // ==========================================
  {
    id: 'd_titan_overlord',
    nameVi: 'Titan Overlord Hủy Diệt',
    nameEn: 'Titan Overlord',
    family: 'dragon',
    category: 'boss',
    tier: 'world-boss',
    baseLevel: 100,
    color: '#0f172a',
    weaknesses: ['holy'],
    skillVi: 'Tàn Phá Thế Giới',
    skillEn: 'World Ruin Strike',
    loreVi: 'Khổng thần thức tỉnh từ sâu trong lõi lục địa, được tạo ra để thanh tẩy thế giới.',
    loreEn: 'Giant celestial construct awakening from earth core, designated to purge realms.',
    hasCrown: true,
    baseHpMult: 8.0,
    baseAtkMult: 3.5,
    baseDefMult: 2.5,
    spawnMinStage: 100,
    spawnMaxStage: 100
  },
  {
    id: 'e_pyro_titan',
    nameVi: 'Khổng Thần Lửa Cự Đại',
    nameEn: 'Great Pyro Titan',
    family: 'elemental',
    category: 'boss',
    tier: 'world-boss',
    baseLevel: 92,
    color: '#b91c1c',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Vũ Điệu Dung Nham',
    skillEn: 'Lava Eruption Wave',
    loreVi: 'Cự thần được rèn từ lò lửa rực đỏ của các vị thần cổ, mang sức nóng nung chảy vạn vật.',
    loreEn: 'Forged in the heart of primeval volcanoes, summoning magma waves to cleanse battlefield.',
    hasCrown: true,
    baseHpMult: 7.2,
    baseAtkMult: 3.2,
    baseDefMult: 2.2,
    spawnMinStage: 92,
    spawnMaxStage: 92
  },
  {
    id: 'e_frost_titan',
    nameVi: 'Khổng Thần Băng Bắc Cực',
    nameEn: 'Glacial Frost Titan',
    family: 'elemental',
    category: 'boss',
    tier: 'world-boss',
    baseLevel: 94,
    color: '#1d4ed8',
    weaknesses: ['fire'],
    skillVi: 'Hàn Băng Tuyệt Diệt',
    skillEn: 'Glacial Avalanche Slam',
    loreVi: 'Khổng thần khổng lồ tạo dựng từ tảng băng trôi ngàn năm, đóng băng ý chí kẻ địch.',
    loreEn: 'Formed from continental shelves of absolute zero glaciers, crushing targets with icy weight.',
    hasCrown: true,
    baseHpMult: 7.5,
    baseAtkMult: 3.0,
    baseDefMult: 2.4,
    spawnMinStage: 94,
    spawnMaxStage: 94
  },
  {
    id: 'd_celestial_dragon',
    nameVi: 'Cổ Long Tinh Không Hoàng Kim',
    nameEn: 'Celestial Golden Dragon',
    family: 'dragon',
    category: 'boss',
    tier: 'world-boss',
    baseLevel: 98,
    color: '#eab308',
    weaknesses: ['dark'],
    skillVi: 'Tinh Vân Bộc Phá',
    skillEn: 'Cosmic Nebula Roar',
    loreVi: 'Rồng thần tối cao ngự trị giữa ngân hà sao sáng, bảo hộ chân lý vương quốc Thượng Giới.',
    loreEn: 'Celestial guardian dragon weaving stellar starlight into cosmic rays of annihilation.',
    hasCrown: true,
    baseHpMult: 7.8,
    baseAtkMult: 3.4,
    baseDefMult: 2.3,
    spawnMinStage: 98,
    spawnMaxStage: 98
  },
  {
    id: 'e_atlas_titan',
    nameVi: 'Thần Đá Đỡ Lục Địa Atlas',
    nameEn: 'Atlas Earth Shaper',
    family: 'elemental',
    category: 'boss',
    tier: 'world-boss',
    baseLevel: 100,
    color: '#1e293b',
    weaknesses: ['ice', 'dark'],
    skillVi: 'Trái Đất Sụp Đổ',
    skillEn: 'Tectonic Cataclysm Slam',
    loreVi: 'Titan chịu tội nâng đỡ bầu trời và lục địa, thân thể hóa thạch cực kỳ kiên cố bất biến.',
    loreEn: 'Primordial elemental titan containing continental shifts within its basalt armor.',
    hasCrown: true,
    baseHpMult: 8.2,
    baseAtkMult: 3.2,
    baseDefMult: 2.8,
    spawnMinStage: 100,
    spawnMaxStage: 100
  }
];
