import { DamageType } from './types/game';

export interface BestiarySpecies {
  id: string;
  nameVi: string;
  nameEn: string;
  family: 'slime' | 'greenskin' | 'undead' | 'elemental' | 'dragon';
  category: 'normal' | 'boss' | 'king' | 'mystery' | 'extinct';
  baseLevel: number;
  color: string;
  weaknesses: DamageType[];
  skillVi: string;
  skillEn: string;
  loreVi: string;
  loreEn: string;
  hasCrown?: boolean;
  baseHpMult: number;
  baseAtkMult: number;
  baseDefMult: number;
  spawnMinStage: number;
  spawnMaxStage: number;
}

export const MONSTER_SPECIES_DATABASE: BestiarySpecies[] = [
  // --- SLIME FAMILY ---
  {
    id: 's_meadow_slime',
    nameVi: 'Slime Thảo Nguyên',
    nameEn: 'Meadow Slime',
    family: 'slime',
    category: 'normal',
    baseLevel: 1,
    color: '#10b981', // green
    weaknesses: ['fire'],
    skillVi: 'Phun Bong Bóng',
    skillEn: 'Bubble Splash',
    loreVi: 'Loài Slime nguyên bản dẻo dai, sinh sống hòa bình tại các vùng thảo nguyên xanh mát.',
    loreEn: 'The original resilient Slime species, peacefully occupying open grasslands.',
    baseHpMult: 1.0,
    baseAtkMult: 1.0,
    baseDefMult: 1.0,
    spawnMinStage: 1,
    spawnMaxStage: 15
  },
  {
    id: 's_granite_slime',
    nameVi: 'Slime Cương Thạch',
    nameEn: 'Granite Slime',
    family: 'slime',
    category: 'normal',
    baseLevel: 8,
    color: '#78716c', // gray
    weaknesses: ['ice'],
    skillVi: 'Giáp Đá Hóa Cương',
    skillEn: 'Stone Shielding',
    loreVi: 'Lõi đá thạch anh siêu cứng bảo vệ chúng khỏi các đòn chém vật lý nặng.',
    loreEn: 'Encased in heavy crystalline granite shield, protecting against physical thrusts.',
    baseHpMult: 1.3,
    baseAtkMult: 0.9,
    baseDefMult: 1.8,
    spawnMinStage: 5,
    spawnMaxStage: 25
  },
  {
    id: 's_magma_slime',
    nameVi: 'Slime Dung Nham',
    nameEn: 'Magma Slime',
    family: 'slime',
    category: 'normal',
    baseLevel: 15,
    color: '#ef4444', // red
    weaknesses: ['ice'],
    skillVi: 'Hỏa Cầu Bộc Phá',
    skillEn: 'Combustion Bomb',
    loreVi: 'Hấp thụ địa nhiệt từ nham thạch nung chảy, phóng ra những đốm lửa thiêu đốt đối thủ.',
    loreEn: 'Formed from underground molten magma, shooting explosive searing projectiles.',
    baseHpMult: 0.9,
    baseAtkMult: 1.5,
    baseDefMult: 0.8,
    spawnMinStage: 10,
    spawnMaxStage: 40
  },
  {
    id: 's_frost_slime',
    nameVi: 'Slime Tuyết Lạnh',
    nameEn: 'Frost Slime',
    family: 'slime',
    category: 'normal',
    baseLevel: 22,
    color: '#3b82f6', // blue
    weaknesses: ['fire'],
    skillVi: 'Hàn Băng Làm Chậm',
    skillEn: 'Freezing Slow',
    loreVi: 'Lớp tuyết lạnh vĩnh cửu bao phủ quanh thân, làm đóng băng và giảm tốc độ đánh mục tiêu.',
    loreEn: 'Coated in eternal freezing frost, slowing targets\' combat speed on contact.',
    baseHpMult: 1.1,
    baseAtkMult: 1.1,
    baseDefMult: 1.1,
    spawnMinStage: 18,
    spawnMaxStage: 50
  },
  {
    id: 's_void_slime',
    nameVi: 'Slime Hắc Ám',
    nameEn: 'Void Slime',
    family: 'slime',
    category: 'normal',
    baseLevel: 30,
    color: '#a855f7', // purple
    weaknesses: ['holy'],
    skillVi: 'Bong Bóng Độc Hư Không',
    skillEn: 'Void Poison Bubble',
    loreVi: 'Sinh vật biến dị do hấp thụ tà khí hắc ám từ cõi hư vô sâu thẳm.',
    loreEn: 'Corrupted lifeforms that fed on dark void particles in deep rifts.',
    baseHpMult: 1.0,
    baseAtkMult: 1.3,
    baseDefMult: 1.0,
    spawnMinStage: 25,
    spawnMaxStage: 70
  },
  {
    id: 's_crystal_slime',
    nameVi: 'Slime Pha Lê',
    nameEn: 'Crystal Slime',
    family: 'slime',
    category: 'mystery',
    baseLevel: 35,
    color: '#06b6d4', // cyan
    weaknesses: ['dark'],
    skillVi: 'Tinh Thể Phản Chiếu',
    skillEn: 'Reflective Spike',
    loreVi: 'Slime hiếm có vỏ bọc pha lê lấp lánh phản chiếu ma pháp. Chỉ gặp ở các ải pha lê sâu.',
    loreEn: 'A rare crystal-coated Slime that refracts magic spells. Found in deep crystalline caves.',
    baseHpMult: 1.2,
    baseAtkMult: 1.2,
    baseDefMult: 1.5,
    spawnMinStage: 30,
    spawnMaxStage: 100
  },
  {
    id: 's_golden_slime',
    nameVi: 'Slime Hoàng Kim (Hiếm)',
    nameEn: 'Golden Slime',
    family: 'slime',
    category: 'mystery',
    baseLevel: 10,
    color: '#fbbf24', // gold
    weaknesses: ['dark', 'fire'],
    skillVi: 'Hào Quang Tài Lộc',
    skillEn: 'Fortune Glow',
    loreVi: 'Sinh vật huyền thoại làm bằng vàng ròng, cực kỳ nhanh nhẹn và giàu có khi tiêu diệt.',
    loreEn: 'A legendary slime made of pure gold. Extremely fast and yields huge wealth when slain.',
    baseHpMult: 2.0,
    baseAtkMult: 0.5,
    baseDefMult: 2.0,
    spawnMinStage: 1,
    spawnMaxStage: 1000
  },
  {
    id: 's_slime_king',
    nameVi: 'Vua Slime Hoàng Gia',
    nameEn: 'Slime King',
    family: 'slime',
    category: 'king',
    baseLevel: 10,
    color: '#eab308',
    weaknesses: ['fire'],
    skillVi: 'Vạn Quân Chấn Động',
    skillEn: 'Royal Slam',
    loreVi: 'Thủ lĩnh tối cao của đầm lầy Slime. Đội vương miện lấp lánh và nhảy đè bẹp kẻ khiêu khích.',
    loreEn: 'The absolute ruler of slimes, crushing challenges with high-altitude jumps.',
    hasCrown: true,
    baseHpMult: 3.5,
    baseAtkMult: 1.8,
    baseDefMult: 1.4,
    spawnMinStage: 10,
    spawnMaxStage: 10
  },
  // --- GREENSKIN FAMILY ---
  {
    id: 'g_forest_goblin',
    nameVi: 'Goblin Rừng Rậm',
    nameEn: 'Forest Goblin',
    family: 'greenskin',
    category: 'normal',
    baseLevel: 12,
    color: '#4ade80', // light green
    weaknesses: ['fire', 'poison'],
    skillVi: 'Móc Túi Nhanh',
    skillEn: 'Quick Mug',
    loreVi: 'Sinh vật ranh ma thường núp bóng cây rừng để cướp bóc các đoàn lữ hành.',
    loreEn: 'Cunning tricksters hiding in dense tree shadows to pillage merchant caravans.',
    baseHpMult: 0.8,
    baseAtkMult: 1.2,
    baseDefMult: 0.7,
    spawnMinStage: 11,
    spawnMaxStage: 35
  },
  {
    id: 'g_goblin_emperor',
    nameVi: 'Hoàng Đế Goblin',
    nameEn: 'Goblin Emperor',
    family: 'greenskin',
    category: 'king',
    baseLevel: 20,
    color: '#84cc16',
    weaknesses: ['fire'],
    skillVi: 'Lệnh Triệu Tập Binh Sĩ',
    skillEn: 'Emperor Summon',
    loreVi: 'Thống trị toàn bộ vương quốc da xanh dưới lòng đất, chỉ huy hàng vạn tay sai phục dịch.',
    loreEn: 'Ruler of the subterranean greenskin empire, commanding hordes of loyal minions.',
    hasCrown: true,
    baseHpMult: 3.8,
    baseAtkMult: 1.9,
    baseDefMult: 1.5,
    spawnMinStage: 20,
    spawnMaxStage: 20
  },
  {
    id: 'g_orc_warrior',
    nameVi: 'Orc Chiến Binh',
    nameEn: 'Orc Warrior',
    family: 'greenskin',
    category: 'normal',
    baseLevel: 32,
    color: '#15803d', // dark forest green
    weaknesses: ['fire', 'ice'],
    skillVi: 'Cuồng Nộ Rìu Chiến',
    skillEn: 'Cleave Frenzy',
    loreVi: 'Đấu sĩ Orc đô con sở hữu sức mạnh cơ bắp đáng sợ, sẵn sàng nghiền nát mọi lá chắn.',
    loreEn: 'Heavy muscular orc gladiators wielding colossal waraxes to crush defenses.',
    baseHpMult: 1.4,
    baseAtkMult: 1.4,
    baseDefMult: 1.2,
    spawnMinStage: 31,
    spawnMaxStage: 65
  },
  {
    id: 'g_orc_chieftain',
    nameVi: 'Orc Tộc Trưởng',
    nameEn: 'Orc Chieftain',
    family: 'greenskin',
    category: 'king',
    baseLevel: 40,
    color: '#166534',
    weaknesses: ['ice'],
    skillVi: 'Chiến Tiếng Rầm Rộ',
    skillEn: 'Warlord Roar',
    loreVi: 'Thủ lĩnh bộ tộc da xanh tàn bạo, được chọn qua hàng trăm cuộc sinh tử đấu đài.',
    loreEn: 'The savage chief of greenskin clans, chosen through hundreds of death arena fights.',
    hasCrown: true,
    baseHpMult: 4.0,
    baseAtkMult: 2.0,
    baseDefMult: 1.6,
    spawnMinStage: 40,
    spawnMaxStage: 40
  },
  // --- UNDEAD FAMILY ---
  {
    id: 'u_skeleton_archer',
    nameVi: 'Cung Thủ Xương',
    nameEn: 'Skeleton Archer',
    family: 'undead',
    category: 'normal',
    baseLevel: 25,
    color: '#cbd5e1', // bone white/slate
    weaknesses: ['holy', 'fire'],
    skillVi: 'Mưa Tên Xương Khô',
    skillEn: 'Bone Arrow Rain',
    loreVi: 'Những cung thủ đã khuất phục sinh dưới tà thuật chiêu hồn, bắn ra mũi tên mang tử khí.',
    loreEn: 'Risen archers animated by necromancy, launching arrows coated in decay.',
    baseHpMult: 0.9,
    baseAtkMult: 1.3,
    baseDefMult: 0.9,
    spawnMinStage: 21,
    spawnMaxStage: 55
  },
  {
    id: 'u_skeleton_warlord',
    nameVi: 'Bạo Chúa Xương Warlord',
    nameEn: 'Skeleton Warlord',
    family: 'undead',
    category: 'king',
    baseLevel: 30,
    color: '#94a3b8',
    weaknesses: ['holy'],
    skillVi: 'Tử Khí Trỗi Dậy',
    skillEn: 'Rise of Undead',
    loreVi: 'Chủ tướng đại quân xác sống cổ đại. Thanh kiếm rỉ sét của hắn uống máu hàng vạn sinh linh.',
    loreEn: 'Commander of ancient undead legions, wielding a cursed heavy claymore.',
    hasCrown: true,
    baseHpMult: 4.2,
    baseAtkMult: 2.1,
    baseDefMult: 1.6,
    spawnMinStage: 30,
    spawnMaxStage: 30
  },
  {
    id: 'u_wraith_lord',
    nameVi: 'Chúa Tể Hồn Ma Wraith',
    nameEn: 'Wraith Lord',
    family: 'undead',
    category: 'king',
    baseLevel: 60,
    color: '#6366f1',
    weaknesses: ['holy', 'fire'],
    skillVi: 'Hồn Hút Hư Vô',
    skillEn: 'Soul Drain',
    loreVi: 'Vua của thế giới linh hồn vất vưởng, một tiếng thét oán than có thể bóp nghẹt tâm trí kẻ thù.',
    loreEn: 'Sovereign of lost spirits, shattering resolve with echoes of eternal torment.',
    hasCrown: true,
    baseHpMult: 4.5,
    baseAtkMult: 2.2,
    baseDefMult: 1.7,
    spawnMinStage: 60,
    spawnMaxStage: 60
  },
  // --- ELEMENTAL / GIANT FAMILY ---
  {
    id: 'e_stone_golem',
    nameVi: 'Golem Đá Cổ Đại',
    nameEn: 'Stone Golem',
    family: 'elemental',
    category: 'normal',
    baseLevel: 45,
    color: '#44403c', // stone brown
    weaknesses: ['ice', 'dark'],
    skillVi: 'Chấn Động Đất Đá',
    skillEn: 'Earthquake Slam',
    loreVi: 'Hộ vệ đền cổ được khắc chữ rune cổ xưa, sừng sững bền bỉ như bàn thạch.',
    loreEn: 'Temple defenders inscribed with ancient runes, standing firm like mountain peaks.',
    baseHpMult: 1.8,
    baseAtkMult: 1.0,
    baseDefMult: 2.2,
    spawnMinStage: 41,
    spawnMaxStage: 85
  },
  {
    id: 'e_golem_guardian',
    nameVi: 'Hộ Vệ Golem Khổng Lồ',
    nameEn: 'Golem Guardian',
    family: 'elemental',
    category: 'king',
    baseLevel: 50,
    color: '#292524',
    weaknesses: ['ice'],
    skillVi: 'Rào Chắn Thiên Thạch',
    skillEn: 'Meteor Barrier',
    loreVi: 'Golem tối cổ canh giữ cổng thần giới, thân thể làm bằng kim loại thiên thạch siêu cứng.',
    loreEn: 'Ancient construct guarding celestial gates, made of meteor alloy.',
    hasCrown: true,
    baseHpMult: 4.8,
    baseAtkMult: 2.3,
    baseDefMult: 1.8,
    spawnMinStage: 50,
    spawnMaxStage: 50
  },
  {
    id: 'e_demon_commander',
    nameVi: 'Thống Lĩnh Quỷ Lửa',
    nameEn: 'Demon Commander',
    family: 'elemental',
    category: 'king',
    baseLevel: 70,
    color: '#dc2626',
    weaknesses: ['ice', 'holy'],
    skillVi: 'Địa Ngục Phẫn Nộ',
    skillEn: 'Hellfire Wrath',
    loreVi: 'Đại tướng quân xứ Abyssal, thống lĩnh binh đoàn quỷ lửa thiêu rụi các lục địa.',
    loreEn: 'Arch-general of abyssal voids, command fire demons to burn civilizations.',
    hasCrown: true,
    baseHpMult: 5.2,
    baseAtkMult: 2.5,
    baseDefMult: 1.8,
    spawnMinStage: 70,
    spawnMaxStage: 70
  },
  // --- DRAGON FAMILY ---
  {
    id: 'd_volcanic_drake',
    nameVi: 'Dực Long Núi Lửa',
    nameEn: 'Volcanic Drake',
    family: 'dragon',
    category: 'normal',
    baseLevel: 65,
    color: '#ea580c', // orange/lava
    weaknesses: ['ice', 'dark'],
    skillVi: 'Phún Trào Hỏa Long',
    skillEn: 'Fire Drake Breath',
    loreVi: 'Sinh vật có cánh thở ra tàn lửa nóng bỏng, thường săn mồi quanh các đỉnh núi lửa hoạt động.',
    loreEn: 'Winged predators nesting near active volcanic calderas, spewing cinder sprays.',
    baseHpMult: 1.2,
    baseAtkMult: 1.5,
    baseDefMult: 1.0,
    spawnMinStage: 61,
    spawnMaxStage: 95
  },
  {
    id: 'd_drake_sovereign',
    nameVi: 'Chúa Tể Dực Long',
    nameEn: 'Drake Sovereign',
    family: 'dragon',
    category: 'king',
    baseLevel: 80,
    color: '#c2410c',
    weaknesses: ['ice'],
    skillVi: 'Hơi Thở Tàn Phá',
    skillEn: 'Sovereign Breath',
    loreVi: 'Vua của loài dực long núi lửa, thống trị bầu trời rực lửa bằng uy áp long tộc.',
    loreEn: 'Overlord of volcanic drakes, ruling the burning sky with imperial dragon presence.',
    hasCrown: true,
    baseHpMult: 5.5,
    baseAtkMult: 2.7,
    baseDefMult: 2.0,
    spawnMinStage: 80,
    spawnMaxStage: 80
  },
  {
    id: 'd_ancient_dragon',
    nameVi: 'Cổ Long Băng Giá (Boss)',
    nameEn: 'Ancient Dragon',
    family: 'dragon',
    category: 'boss',
    baseLevel: 90,
    color: '#0284c7', // light blue dragon
    weaknesses: ['fire', 'dark'],
    skillVi: 'Hơi Thở Hàn Băng Tuyệt Diệt',
    skillEn: 'Absolute Zero Breath',
    loreVi: 'Rồng cổ đại sống ngàn năm trong băng tuyết vĩnh cửu. Một hơi thở đóng băng vạn vật.',
    loreEn: 'Thousand-year-old dragon sleeping in glacial peaks, turning challengers into solid ice.',
    hasCrown: true,
    baseHpMult: 6.0,
    baseAtkMult: 3.0,
    baseDefMult: 2.2,
    spawnMinStage: 90,
    spawnMaxStage: 90
  },
  {
    id: 'd_titan_overlord',
    nameVi: 'Titan Overlord Hủy Diệt',
    nameEn: 'Titan Overlord',
    family: 'dragon',
    category: 'boss',
    baseLevel: 100,
    color: '#0f172a', // dark titan
    weaknesses: ['holy'],
    skillVi: 'Tàn Phá Thế Giới',
    skillEn: 'World Ruin Strike',
    loreVi: 'Khổng thần thức tỉnh từ sâu trong lõi lục địa, được tạo ra để thanh tẩy thế giới.',
    loreEn: 'Giant celestial construct awakening from earth core, designated to purge realms.',
    hasCrown: true,
    baseHpMult: 8.0,
    baseAtkMult: 3.5,
    baseDefMult: 2.5,
    spawnMinStage: 100,
    spawnMaxStage: 100
  },
  // --- SECRET BOSSES CAN ALSO BE UNLOCKED ---
  {
    id: 's_ancient_slime_god',
    nameVi: 'Thần Slime Cổ Đại Canh Giữ (Huyền Thoại)',
    nameEn: 'Primordial Slime God',
    family: 'slime',
    category: 'extinct',
    baseLevel: 50,
    color: '#4f46e5', // royal blue-purple
    weaknesses: ['holy', 'dark'],
    skillVi: 'Hào Quang Hỗn Hợp',
    skillEn: 'Primordial Aura Burst',
    loreVi: 'Tổ mẫu tối cổ của vạn vật dẻo dai. Thần thức của nó trỗi dậy khi người chơi tiêu diệt hơn 100 Slime.',
    loreEn: 'Primordial deity of gelatinous organisms. Awakens when Meadow Slime species drops critical numbers.',
    hasCrown: true,
    baseHpMult: 7.5,
    baseAtkMult: 3.0,
    baseDefMult: 2.0,
    spawnMinStage: 999, // Hidden trigger
    spawnMaxStage: 999
  }
];
